name: waterdynamics-docs
channels:

  - conda-forge

dependencies:
    # Base depends
  - python
  - pip

  - mdanalysis-sphinx-theme >=1.0.1
  - sphinxcontrib-bibtex
  # Temporary pin whilst we don't support numpy 2.0 upstream
  - numpy <2.0
    # Pip-only installs
  #- pip:
