name: waterdynamics-docs
channels:

  - conda-forge

dependencies:
    # Base depends
  - python
  - pip

  - mdanalysis-sphinx-theme >=1.0.1
  - sphinxcontrib-bibtex
    # Pip-only installs
  #- pip:
